### ISSUE TITLE
GIF Support

### ISSUE THREAD

**Issue by zetzrn** [gotschmarcel/instapaper#1]
### program **_aborts**_ when downloading GIF from API

check filetype of downloaded file (API may provide URL to video or text entry?)

to make up for lost image
- recalc columns or spacing, maybe
- duplicate an image

**Comment by gotschmarcel** [comment]
Do you may have an example account providing gif images?

**Comment by zetzrn** [comment]
Ok, program does not abort
but does not build new wallpaper, although it says so

`[rommen] @ ~  $ instapaper -api tumblr -key *api_key* -profile poised-madness`
`2016/05/19 16:47:24 Creating data directory "/home/rommen/.instapaper"`
`2016/05/19 16:47:24 Data directory already exists`
`2016/05/19 16:47:24 Fetched 18 media items`
`2016/05/19 16:47:24 Found 19 cached images`
`2016/05/19 16:47:24 Downloading new version of "143746276120"`
`[...]`
`2016/05/19 16:47:25 Download of '143746276120' complete`
`2016/05/19 16:47:26 Error: Reading image body of "https://67.media.tumblr.com/6eb46116d183e7fa8026d5eaa466db6d/tumblr_o6qhr1ZPaX1ugp61po1_500.gif", image: unknown format`
`[...]`
`2016/05/19 16:47:26 Building wallpaper (2560x1440)`
`2016/05/19 16:47:27 Fatal: open /home/rommen/.instapaper/143941814688: no such file or directory`

**Comment by gotschmarcel** [comment]
The error occurs during the build. It tries to open a file that seems to be non existing. It's probably the gif image which wasn't downloaded due to the error.

**Comment by zetzrn** [comment]
> it's probably the gif image which wasn't downloaded due to the error.
> `tumblr_o6qhr1ZPaX1ugp61po1_500.gif", image:`

![yds](https://cloud.githubusercontent.com/assets/19472858/15399574/87426696-1de8-11e6-8483-08b1c72a98aa.png)
