### ISSUE TITLE
Background Patterns

### ISSUE THREAD

**Issue by zetzrn** [gotschmarcel/instapaper#2]
### Support for background patterns

would be nice to add an option for bg patterns (eg.: subtlepatterns.com)

![wallpapers_patterndemo2](https://cloud.githubusercontent.com/assets/19472858/15396509/cb2e768a-1ddc-11e6-9cc0-617bff1585ff.jpg)
![wallpapers_patterndemo3](https://cloud.githubusercontent.com/assets/19472858/15396510/cb351440-1ddc-11e6-80bb-7e3745f14307.jpg)
![wallpapers_patterndemo](https://cloud.githubusercontent.com/assets/19472858/15396511/cb38e200-1ddc-11e6-9478-4a814319c935.jpg)

**Comment by gotschmarcel** [comment]
Release `v1.5.0` now includes `-pattern file`.
