### ISSUE TITLE
[Linux, Gnome, GDM] Lockscreen Wallpaper

### ISSUE THREAD

**Issue by zetzrn** [gotschmarcel/instapaper#3]
### Lockscreen Wallpaper

modify `-set` option to apply lockscreen wallpaper
- `-set`   or   `-set bg`   as default to set wallpaper
- `-set lock`   as option to set lockscreen wallpaper in gnome-shell/GDM

**Comment by gotschmarcel** [comment]
I added an additional flag called `-set-lockscreen`.
